### ISSUE TITLE
Delete duplicate itens

### ISSUE THREAD

**Issue by marcosvpj** [mb21/JSONedit#12]
After I delete a item from a list , when I edit another item in the same list the edited item has his value updated and the next item too.

I am using this list:

{  "import": [
    "frontend.components._",
    "common.helpers.ciHelpers._",
    "frontend.models._",
    "backend.models._",
    "common.modules.configuracao.ConfiguracaoModule",
    "backend.components._",
    "common.extensions.components._",
    "common.components._",
    "common.helpers._",
    "common.models._",
    "common.utils._",
    "common.validators._",
    "bootstrap.helpers._",
    "application.controllers._",
    "application.extensions._",
    "application.helpers._",
    "application.models._",
    "common.modules.usuario.models._",
    "common.modules.usuario.components._",
    "backend.modules.faq.models.*"
  ]
  }

**Comment by mb21** [comment]
Thanks, fixed with b5d7898a950a2787f91991ae1281e7a043cb841f
