### ISSUE TITLE
change type of property causes odd behavior

### ISSUE THREAD

**Issue by southbite** [mb21/JSONedit#14]
Howdy - great little directive, I am using it for the UI of an API service I am building: https://github.com/southbite/freebase
The UI project is called https://github.com/southbite/freebase-ui

Anyhoo, I found an odd little behaviour that I haven't been able solve, if you change a property type from array to text in scope keeping the property name the same - the old html for the old property is not removed, and is no longer wired to click events

example json:

{
  "property": ["some text"]
}

changes to 

{
  "property": "some text"
}

You can see this in action on your demo page by simply pasting the json in my example in the above order.

**Comment by CaptainYarb** [comment]
I can confirm this issue also affects booleans. Very frustrating

**Comment by mb21** [comment]
I think this is fixed now. Let me know if you can still reproduce it somehow.
