### ISSUE TITLE
Large JSON file refresh time on ng-change

### ISSUE THREAD

**Issue by ghost** [mb21/JSONedit#16]
Issue with long JSON file (1 mb): the ng-change and ng-model-onblur takes a long time.

`<input type="text" ng-model="val" placeholder="Empty" ng-model-onblur ng-change="child[key] = possibleNumber(val)"/>`

For some reason the ng-model-onblur isn't waiting for the blur event and is causing a refresh after a single edit.

I would prefer a changeset model and an update button.  Unfortunately I think this may mean removing the watch() statements in the controller and the runtime binding, unless we can somehow do it asynchronously.

Additionally, ng-change causes the tree to refresh.  On mine I've set the default state to collapsed.

**Comment by mb21** [comment]
Yes, Angular has been known to get slow with large data sets. Of course we could introduce "update" buttons but that would kind of miss the whole point of Angular's data bindings.

**Comment by ghost** [comment]
In the version we are using now, which is based upon your tree, we don't use the blur event.  It loads a fairly massive JSON file, but uses several angular filters to prune it out.  It also uses a separate tree service that monitors the tree.

In short: it works wonderfully especially if we can remove as many _function calls from partials_ that are looped from within the angular recursion of the json tree.  Instead, pack the data into JS objects ahead of time.

Thanks for your help.

**Comment by mb21** [comment]
Glad to hear that it's working for you.
