### ISSUE TITLE
properties with underscores

### ISSUE THREAD

**Issue by DominicBoettger** [mb21/JSONedit#21]
Hello,

properties with underscores ares not allowed and it's not possible to override this behaviour.

Best regards
Dominic

**Comment by nachokb** [comment]
@DominicBoettger not sure what you mean... I can create keys with underscores

![image](https://cloud.githubusercontent.com/assets/17967/6031760/dcf95b7e-abe0-11e4-8154-d57b837dd72e.png)

**Comment by DominicBoettger** [comment]
It does not work if the key starts with the underscore.

**Comment by nachokb** [comment]
oh ok thanks didn't get that... it's reasonable

**Comment by mb21** [comment]
yeah, I put that in because some frameworks etc. save private stuff in properties starting with an underscore...
