### ISSUE TITLE
Few ideas

### ISSUE THREAD

**Issue by ninoCookies** [mb21/JSONedit#22]
For simple projects that run from .json files it would be awesome if JSONedit would allow adding whole new objects (not just properties) and also remove whole Objects. Aswell would it be possible to add "Save" button that would save all the changes to json file ?
(I will try to add those features myself, though i'm begginer in the field od AngularJS)
Otherwise, great work on it.

**Comment by mb21** [comment]
You can add Objects and Arrays by selecting them in the drop-down after you click the plus.

I don't want to add too many additional widgets like save-buttons, to make the library not too complex. But it's relatively easy to add one yourself. Good luck!
