### ISSUE TITLE
cannot create native boolean type

### ISSUE THREAD

**Issue by jfairley** [mb21/JSONedit#23]
If I create a "text" node, numbers are automatically interpreted, but not booleans. Entering `true` yields `"true"` in the JSON.

**Comment by capaj** [comment]
:+1:  I think there should be an input for each valid JSON type. Number, String, Boolean, Array, Object and null.

**Comment by mb21** [comment]
Sure, I just haven't gotten around to that... happy to accept a pull request though.

**Comment by jfairley** [comment]
@mb21 When I opened the Issue, I started on the fix myself. It only halfway works right now though (create shows a checkbox, but edit shows a text input), and I got pulled away to some non-angular responsibilities. I do plan to finish it up and PR, but I can't say when. I'm sure you could say something similar. :stuck_out_tongue:

**Comment by nachokb** [comment]
@jfairley do you mind publishing your wip branch? thanks!

**Comment by jfairley** [comment]
@nachokb Sorry for not getting back in time. I just went to rebase my changes, and found that @dustinsmith1024 implemented almost exactly what I had done locally. Thanks guys!

**Comment by dustinsmith1024** [comment]
I think there might be a small CSS issue.  @jfairley did you notice that at all?

**Comment by jfairley** [comment]
Yeah, CSS was the first place I was stuck. For me the checkbox was too big and not aligned.
