### ISSUE TITLE
editing values on array does not update json

### ISSUE THREAD

**Issue by nachokb** [mb21/JSONedit#26]
Reproduced it on the example [1], please watch youtube video below [2].

When editing a value, it works ok for all types, save for arrays, which do not update to JSON result. This can get confusing.

There are other times in which editing the textarea does not bind correctly, still investigating that.

[1] http://mb21.github.io/JSONedit/
[2] https://www.youtube.com/watch?v=VuNzcEk8ub4

**Comment by verygoodsoftwarenotvirus** [comment]
I can confirm I experience this bug as well.
