### ISSUE TITLE
Each key input loses focus on change

### ISSUE THREAD

**Issue by jpillora** [mb21/JSONedit#3]

**Comment by mb21** [comment]
Thanks! fixed by updating angular.

**Comment by jpillora** [comment]
:+1:

**Comment by jpillora** [comment]
Hmm still seems to be happening actually, I'm on Mac OSX 10.8.4 Chrome 29.0.1547.65

**Comment by mb21** [comment]
Probably takes a few minutes to propagate the changes to github pages. If still no effect, clear your browser cache.

**Comment by jpillora** [comment]
Once setup, Github Pages propagation is on push, I have a feeling they
reference the files directly in the repo. Still same for me.

**Comment by mb21** [comment]
Clear your browser cache. It's working for me on Mac OS X 10.8.5 Chrome  29.0.1547.65

**Comment by lukasz-kaniowski** [comment]
i've just tried this on firefox safari and chrome and it still seems to be broken. any suggestions how to fix it?

**Comment by XavierP56** [comment]
Hi, 
On Linux chrome, I do have the problem !

**Comment by mb21** [comment]
Seems to happen when Angular.js refreshes the view... We've had this before and the following attribute-directive used to fix it, but it's producing inconsistent results now:

```
app.directive('focus', function() {
    return {
        restrict: 'A',
        link: function(scope, element, attributes) {
            element[0].focus();
        }
    }
});

<input type="text" focus />
```

**Comment by XavierP56** [comment]
Any solution ?

**Comment by lukasz-kaniowski** [comment]
+1

**Comment by liuyu121** [comment]
yeah,it still in the mac os x with chrom 36.0.1985.125

**Comment by mb21** [comment]
Okay, I now changed it to only update the angular model when you leave the text box (i.e. using on-blur instead of on-change).
