### ISSUE TITLE
Bower component doesn't include Boolean capability

### ISSUE THREAD

**Issue by bitwit** [mb21/JSONedit#31]
I think there must be some difference between V0.2.0 that you get form `bower install --save json-edit` and what is in the demo mode because I can see the `directives.js` doesn't include a `Boolean` type.

Probably just needs a quick republish. I can see that the .zip folder on github for version 0.2.0 also does not include the Boolean capability.

Cheers

**Comment by mb21** [comment]
Thanks, I haven't tagged a new version for bower in a while, just pushed v0.2.1 now.
