### ISSUE TITLE
jQuery dependency

### ISSUE THREAD

**Issue by futurechan** [mb21/JSONedit#32]
I looked at the `JSONedit.js` and `directives.js` files, and I don't see any jquery  dependency. Is it really necessary that I add jquery to my page?

**Comment by futurechan** [comment]
It looks like the jQuery dependency is unnecessary.

**Comment by mb21** [comment]
Unfortunately, [angular-ui-sortable](https://github.com/angular-ui/ui-sortable) requires it...
