### ISSUE TITLE
Back-end Integration

### ISSUE THREAD

**Issue by caiovaccaro** [mb21/JSONedit#33]
Hi there!

I just forked your project and will try to integrate with a simple Back-End (probably node.js) so that your script save the changes made to a given .json file.

Do you have any interest of a pull request with such changes?

**Comment by mb21** [comment]
Thanks, but I'm intending to keep this a simple client-side angular directive, but feel free to add your project to [the wiki](https://github.com/mb21/JSONedit/wiki)!
