### ISSUE TITLE
Missing Semicolons

### ISSUE THREAD

**Issue by stefanlorenz85** [mb21/JSONedit#38]
Missing semicolons line 35+36 in js/directives.js

```
var boolName = "Boolean"
var numberName = "Number"
```

https://github.com/mb21/JSONedit/commit/ac0c79281b1de124f977877ffcc9365735469876

**Comment by mb21** [comment]
thanks, fixed with https://github.com/mb21/JSONedit/commit/692dfa567e95e38afdd6d499a8e6a88d71a1ea31
