### ISSUE TITLE
create master branch

### ISSUE THREAD

**Issue by dwelch2344** [mb21/JSONedit#42]
We're using NPM instead of bower (per or Front End engineer's request) and having issues pulling your project due to a missing master branch. Any reason you don't have one? Would you mind making one?

**Comment by mb21** [comment]
The reason is that when using `gh-pages` I get a live-demo for free without having to deal with an additional branch...

But actually, NPM [supports git URLs from different branches](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies). Something like:

```
git://github.com/mb21/JSONedit.git#gh-pages
```

**Comment by dwelch2344** [comment]
Yeah, we tried that but for some reason it doesn't work. Wondering if they have an implicit check for master before targeting the specified branch. We ended up forking and creating master & things worked fine. Works for now I guess

**Comment by MatissJanis** [comment]
We have exactly the same problem. Would be great to see this repo published as a NPM package.
