### ISSUE TITLE
Reordering list elements causes numbers to go out of sync

### ISSUE THREAD

**Issue by shalotelli** [mb21/JSONedit#6]
When reordering list elements, the order numbers to the left go out of sync. It seems this is a pretty common problem with jQuery sortable and one that i've had before. It happens because when dragging, jQuery adds another element to the list which throws everything off. I solved it by doing the following:
1. Set the newly added elements class to something different then the standard.

``` javascript
$(function() {
       $(el).sortable({
           placeholder: 'sortable-placeholder'
       });
});
```
1. Add the following CSS styling to the placeholder

``` css
.sortable-placeholder {
       height: 20px;
       display: block;
}
```

https://gist.github.com/shalotelli/6597324

**Comment by mb21** [comment]
Thanks, for the code. Integrated and working. 84a3c3f2922fe88d55dd84c74aa7ae92c17431ea

**Comment by shalotelli** [comment]
looks great
