### ISSUE TITLE
Delete key badly supported

### ISSUE THREAD

**Issue by XavierP56** [mb21/JSONedit#9]
On a root node, delete twice: The second delete is sent to the browser !

**Comment by mb21** [comment]
What? sorry, care to explain exactly what the issue is? pull request welcomed as well ;)

**Comment by XavierP56** [comment]
Simple. Go on your "try it" page.
Click on the first node "Address". Type Del key twice : The browser goes back !
Using Chrome on Linux.

**Comment by mb21** [comment]
Ah, that's because of issue #3
